# Preset was created in ADB AppControl 1.7.1
# Total applications: 322
# 10/31/2021 6:05 PM
# Samsung SM-A315G Deleted applications
android.auto_generated_rro_product__
android.auto_generated_rro_vendor__
android.autoinstalls.config.samsung
com.android.apps.tag
com.android.backupconfirm
com.android.bips
com.android.bluetoothmidiservice
com.android.bookmarkprovider
com.android.calllogbackup
com.android.carrierdefaultapp
com.android.certinstaller
com.android.companiondevicemanager
com.android.cts.ctsshim
com.android.cts.priv.ctsshim
com.android.dreams.basic
com.android.dreams.phototable
com.android.dynsystem
com.android.egg
com.android.emergency
com.android.hotspot2.osulogin
com.android.internal.display.cutout.emulation.corner
com.android.internal.display.cutout.emulation.double
com.android.internal.display.cutout.emulation.hole
com.android.internal.display.cutout.emulation.tall
com.android.internal.display.cutout.emulation.waterfall
com.android.internal.systemui.navbar.gestural
com.android.internal.systemui.navbar.gestural_extra_wide_back
com.android.internal.systemui.navbar.gestural_narrow_back
com.android.internal.systemui.navbar.gestural_wide_back
com.android.internal.systemui.navbar.threebutton
com.android.keychain
com.android.localtransport
com.android.managedprovisioning
com.android.mms.service
com.android.nfc
com.android.ons
com.android.pacprocessor
com.android.printspooler
com.android.providers.partnerbookmarks
com.android.providers.userdictionary
com.android.proxyhandler
com.android.se
com.android.settings.intelligence
com.android.sharedstoragebackup
com.android.simappdialog
com.android.statementservice
com.android.stk
com.android.stk2
com.android.storagemanager
com.android.theme.color.black
com.android.theme.color.cinnamon
com.android.theme.color.green
com.android.theme.color.ocean
com.android.theme.color.orchid
com.android.theme.color.purple
com.android.theme.color.space
com.android.theme.font.notoserifsource
com.android.theme.icon.pebble
com.android.theme.icon.roundedrect
com.android.theme.icon.squircle
com.android.theme.icon.taperedrect
com.android.theme.icon.teardrop
com.android.theme.icon.vessel
com.android.theme.icon_pack.circular.android
com.android.theme.icon_pack.circular.launcher
com.android.theme.icon_pack.circular.settings
com.android.theme.icon_pack.circular.systemui
com.android.theme.icon_pack.circular.themepicker
com.android.theme.icon_pack.filled.android
com.android.theme.icon_pack.filled.launcher
com.android.theme.icon_pack.filled.settings
com.android.theme.icon_pack.filled.systemui
com.android.theme.icon_pack.filled.themepicker
com.android.theme.icon_pack.rounded.android
com.android.theme.icon_pack.rounded.launcher
com.android.theme.icon_pack.rounded.settings
com.android.theme.icon_pack.rounded.systemui
com.android.theme.icon_pack.rounded.themepicker
com.android.traceur
com.android.wallpaper.livepicker
com.android.wallpaperbackup
com.android.wallpapercropper
com.aura.oobe.samsung.gl
com.debug.loggerui
com.diotek.sec.lookup.dictionary
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.google.android.apps.carrier.carrierwifi
com.google.android.apps.restore
com.google.android.apps.tachyon
com.google.android.apps.turbo
com.google.android.as
com.google.android.cellbroadcastreceiver
com.google.android.cellbroadcastservice
com.google.android.configupdater
com.google.android.ext.services
com.google.android.ext.shared
com.google.android.feedback
com.google.android.gms.location.history
com.google.android.googlequicksearchbox
com.google.android.networkstack.permissionconfig
com.google.android.onetimeinitializer
com.google.android.overlay.gmsconfig.common
com.google.android.overlay.gmsconfig.gsa
com.google.android.overlay.gmsconfig.photos
com.google.android.overlay.modules.cellbroadcastreceiver
com.google.android.overlay.modules.cellbroadcastservice
com.google.android.overlay.modules.ext.services
com.google.android.overlay.modules.modulemetadata.forframework
com.google.android.overlay.modules.permissioncontroller.forframework
com.google.android.partnersetup
com.google.android.printservice.recommendation
com.google.android.projection.gearhead
com.google.android.setupwizard
com.google.android.tts
com.google.ar.core
com.google.mainline.telemetry
com.hiya.star
com.knox.vpn.proxyhandler
com.mediatek
com.mediatek.systemuiresoverlay
com.microsoft.appmanager
com.microsoft.skydrive
com.monotype.android.font.foundation
com.monotype.android.font.samsungone
com.netflix.mediaclient
com.netflix.partner.activation
com.osp.app.signin
com.samsung.aasaservice
com.samsung.adaptivebrightnessgo
com.samsung.advp.imssettings
com.samsung.android.accessibility.talkback
com.samsung.android.aircommandmanager
com.samsung.android.allshare.service.fileshare
com.samsung.android.allshare.service.mediashare
com.samsung.android.app.appsedge
com.samsung.android.app.clipboardedge
com.samsung.android.app.cocktailbarservice
com.samsung.android.app.galaxyfinder
com.samsung.android.app.omcagent
com.samsung.android.app.reminder
com.samsung.android.app.settings.bixby
com.samsung.android.app.sharelive
com.samsung.android.app.simplesharing
com.samsung.android.app.smartcapture
com.samsung.android.app.soundpicker
com.samsung.android.app.spage
com.samsung.android.app.taskedge
com.samsung.android.app.watchmanagerstub
com.samsung.android.appseparation
com.samsung.android.ardrawing
com.samsung.android.aremoji
com.samsung.android.aremojieditor
com.samsung.android.arzone
com.samsung.android.authfw
com.samsung.android.aware.service
com.samsung.android.bbc.bbcagent
com.samsung.android.beaconmanager
com.samsung.android.bixbyvision.framework
com.samsung.android.bluelightfilter
com.samsung.android.brightnessbackupservice
com.samsung.android.callbgprovider
com.samsung.android.cidmanager
com.samsung.android.cmfa.framework
com.samsung.android.container
com.samsung.android.da.daagent
com.samsung.android.dqagent
com.samsung.android.dsms
com.samsung.android.dynamiclock
com.samsung.android.easysetup
com.samsung.android.fmm
com.samsung.android.forest
com.samsung.android.game.gamehome
com.samsung.android.game.gametools
com.samsung.android.hdmapp
com.samsung.android.icecone
com.samsung.android.kidsinstaller
com.samsung.android.knox.analytics.uploader
com.samsung.android.knox.attestation
com.samsung.android.knox.containeragent
com.samsung.android.knox.containercore
com.samsung.android.knox.pushmanager
com.samsung.android.livestickers
com.samsung.android.localeoverlaymanager
com.samsung.android.location
com.samsung.android.lool
com.samsung.android.mapsagent
com.samsung.android.mateagent
com.samsung.android.mcfds
com.samsung.android.mcfserver
com.samsung.android.mdecservice
com.samsung.android.mdm
com.samsung.android.mdx
com.samsung.android.mdx.kit
com.samsung.android.mdx.quickboard
com.samsung.android.mobileservice
com.samsung.android.motionphoto.viewer
com.samsung.android.net.wifi.wifiguider
com.samsung.android.networkdiagnostic
com.samsung.android.networkstack
com.samsung.android.networkstack.tethering.overlay
com.samsung.android.privateshare
com.samsung.android.providers.carrier
com.samsung.android.rubin.app
com.samsung.android.samsungpass
com.samsung.android.samsungpassautofill
com.samsung.android.scloud
com.samsung.android.scs
com.samsung.android.sdk.handwriting
com.samsung.android.sdm.config
com.samsung.android.secsoundpicker
com.samsung.android.securitylogagent
com.samsung.android.server.wifi.mobilewips
com.samsung.android.service.peoplestripe
com.samsung.android.service.stplatform
com.samsung.android.setting.multisound
com.samsung.android.SettingsReceiver
com.samsung.android.shortcutbackupservice
com.samsung.android.sm.devicesecurity
com.samsung.android.sm.policy
com.samsung.android.smartcallprovider
com.samsung.android.smartface
com.samsung.android.smartmirroring
com.samsung.android.smartsuggestions
com.samsung.android.smartswitchassistant
com.samsung.android.spayfw
com.samsung.android.stickercenter
com.samsung.android.svcagent
com.samsung.android.tadownloader
com.samsung.android.tapack.authfw
com.samsung.android.themecenter
com.samsung.android.themestore
com.samsung.android.uds
com.samsung.android.visionintelligence
com.samsung.android.wallpaper.res
com.samsung.android.wifi.resources
com.samsung.android.wifi.softap.resources
com.samsung.app.newtrim
com.samsung.cmh
com.samsung.crane
com.samsung.faceservice
com.samsung.ims.smk
com.samsung.internal.systemui.navbar.gestural_no_hint
com.samsung.internal.systemui.navbar.gestural_no_hint_extra_wide_back
com.samsung.internal.systemui.navbar.gestural_no_hint_narrow_back
com.samsung.internal.systemui.navbar.gestural_no_hint_wide_back
com.samsung.internal.systemui.navbar.sec_gestural
com.samsung.internal.systemui.navbar.sec_gestural_no_hint
com.samsung.ipservice
com.samsung.klmsagent
com.samsung.knox.keychain
com.samsung.knox.securefolder
com.samsung.memorysaver
com.samsung.rcs
com.samsung.safetyinformation
com.samsung.sec.android.application.csc
com.samsung.SMT
com.samsung.storyservice
com.sec.android.app.billing
com.sec.android.app.bluetoothtest
com.sec.android.app.chromecustomizations
com.sec.android.app.DataCreate
com.sec.android.app.factorykeystring
com.sec.android.app.fm
com.sec.android.app.hwmoduletest
com.sec.android.app.magnifier
com.sec.android.app.parser
com.sec.android.app.personalization
com.sec.android.app.quicktool
com.sec.android.app.ringtoneBR
com.sec.android.app.safetyassurance
com.sec.android.app.samsungapps
com.sec.android.app.SecSetupWizard
com.sec.android.app.servicemodeapp
com.sec.android.app.setupwizardlegalprovider
com.sec.android.app.soundalive
com.sec.android.app.ve.vebgm
com.sec.android.app.wlantest
com.sec.android.autodoodle.service
com.sec.android.daemonapp
com.sec.android.diagmonagent
com.sec.android.easyMover.Agent
com.sec.android.easyonehand
com.sec.android.emergencylauncher
com.sec.android.emergencymode.service
com.sec.android.mimage.avatarstickers
com.sec.android.mimage.photoretouching
com.sec.android.preloadinstaller
com.sec.android.provider.badge
com.sec.android.provider.emergencymode
com.sec.android.RilServiceModeApp
com.sec.android.soagent
com.sec.android.widgetapp.easymodecontactswidget
com.sec.android.widgetapp.webmanual
com.sec.app.RilErrorNotifier
com.sec.automation
com.sec.bcservice
com.sec.enterprise.knox.attestation
com.sec.enterprise.knox.cloudmdm.smdms
com.sec.enterprise.mdm.services.simpin
com.sec.epdg
com.sec.epdgtestapp
com.sec.factory
com.sec.factory.camera
com.sec.factory.cameralyzer
com.sec.hearingadjust
com.sec.imslogger
com.sec.imsservice
com.sec.location.nfwlocationprivacy
com.sec.location.nsflp2
com.sec.mhs.smarttethering
com.sec.phone
com.sec.spp.push
com.sec.sve
com.sec.unifiedwfc
com.sec.vsim.ericssonnsds.webapp
com.skms.android.agent
com.trustonic.teeservice
com.wsomacp
com.wssyncmldm
