adb shell
pm uninstall --user 0 com.sec.android.app.samsungapps
pm uninstall --user 0 com.google.android.settings.intelligence
pm uninstall --user 0 com.android.imsserviceentitlement
pm uninstall --user 0 com.android.cellbroadcastreceiver
pm uninstall --user 0 android.autoinstalls.config.samsung
pm uninstall --user 0 com.android.apps.tag
pm uninstall --user 0 com.android.backupconfirm
pm uninstall --user 0 com.android.bips
pm uninstall --user 0 com.android.bluetoothmidiservice
pm uninstall --user 0 com.android.bookmarkprovider
pm uninstall --user 0 com.android.calllogbackup
pm uninstall --user 0 com.android.carrierdefaultapp
pm uninstall --user 0 com.android.certinstaller
pm uninstall --user 0 com.android.companiondevicemanager
pm uninstall --user 0 com.android.cts.ctsshim
pm uninstall --user 0 com.android.cts.priv.ctsshim
pm uninstall --user 0 com.android.dreams.basic
pm uninstall --user 0 com.android.dreams.phototable
pm uninstall --user 0 com.android.dynsystem
pm uninstall --user 0 com.android.egg
pm uninstall --user 0 com.android.emergency
pm uninstall --user 0 com.android.hotspot2.osulogin
pm uninstall --user 0 com.android.internal.display.cutout.emulation.corner
pm uninstall --user 0 com.android.internal.display.cutout.emulation.double
pm uninstall --user 0 com.android.internal.display.cutout.emulation.hole
pm uninstall --user 0 com.android.internal.display.cutout.emulation.tall
pm uninstall --user 0 com.android.internal.display.cutout.emulation.waterfall
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_narrow_back
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_wide_back
pm uninstall --user 0 com.android.internal.systemui.navbar.threebutton
pm uninstall --user 0 com.android.managedprovisioning
pm uninstall --user 0 com.android.managedprovisioning.auto_generated_rro_product__
pm uninstall --user 0 com.android.nfc
pm uninstall --user 0 com.android.providers.partnerbookmarks
pm uninstall --user 0 com.android.providers.userdictionary
pm uninstall --user 0 com.android.proxyhandler
pm uninstall --user 0 com.android.se
pm uninstall --user 0 com.android.settings.intelligence
pm uninstall --user 0 com.android.sharedstoragebackup
pm uninstall --user 0 com.android.simappdialog
pm uninstall --user 0 com.android.stk
pm uninstall --user 0 com.android.stk2
pm uninstall --user 0 com.android.storagemanager
pm uninstall --user 0 com.android.theme.color.black
pm uninstall --user 0 com.android.theme.color.cinnamon
pm uninstall --user 0 com.android.theme.color.green
pm uninstall --user 0 com.android.theme.color.ocean
pm uninstall --user 0 com.android.theme.color.orchid
pm uninstall --user 0 com.android.theme.color.purple
pm uninstall --user 0 com.android.theme.color.space
pm uninstall --user 0 com.android.theme.font.notoserifsource
pm uninstall --user 0 com.android.theme.icon.pebble
pm uninstall --user 0 com.android.theme.icon.roundedrect
pm uninstall --user 0 com.android.theme.icon.squircle
pm uninstall --user 0 com.android.theme.icon.taperedrect
pm uninstall --user 0 com.android.theme.icon.teardrop
pm uninstall --user 0 com.android.theme.icon.vessel
pm uninstall --user 0 com.android.theme.icon_pack.circular.android
pm uninstall --user 0 com.android.theme.icon_pack.circular.launcher
pm uninstall --user 0 com.android.theme.icon_pack.circular.settings
pm uninstall --user 0 com.android.theme.icon_pack.circular.systemui
pm uninstall --user 0 com.android.theme.icon_pack.circular.themepicker
pm uninstall --user 0 com.android.theme.icon_pack.filled.android
pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
pm uninstall --user 0 com.android.theme.icon_pack.filled.settings
pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui
pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
pm uninstall --user 0 com.android.theme.icon_pack.rounded.android
pm uninstall --user 0 com.android.theme.icon_pack.rounded.launcher
pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings
pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui
pm uninstall --user 0 com.android.theme.icon_pack.rounded.themepicker
pm uninstall --user 0 com.android.traceur
pm uninstall --user 0 com.android.wallpaper.livepicker
pm uninstall --user 0 com.android.wallpaperbackup
pm uninstall --user 0 com.android.wallpapercropper
pm uninstall --user 0 com.aura.oobe.samsung.gl
pm uninstall --user 0 com.debug.loggerui
pm uninstall --user 0 com.diotek.sec.lookup.dictionary
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.google.android.apps.carrier.carrierwifi
pm uninstall --user 0 com.google.android.apps.restore
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.google.android.apps.turbo
pm uninstall --user 0 com.google.android.as
pm uninstall --user 0 com.google.android.configupdater
pm uninstall --user 0 com.google.android.feedback
pm uninstall --user 0 com.google.android.gms.location.history
pm uninstall --user 0 com.google.android.googlequicksearchbox
pm uninstall --user 0 com.google.android.networkstack.permissionconfig
pm uninstall --user 0 com.google.android.overlay.gmsconfig.common
pm uninstall --user 0 com.google.android.overlay.gmsconfig.gsa
pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos
pm uninstall --user 0 com.google.android.overlay.modules.ext.services
pm uninstall --user 0 com.google.android.overlay.modules.modulemetadata.forframework
pm uninstall --user 0 com.google.android.overlay.modules.permissioncontroller.forframework
pm uninstall --user 0 com.google.android.partnersetup
pm uninstall --user 0 com.google.android.printservice.recommendation
pm uninstall --user 0 com.google.android.projection.gearhead
pm uninstall --user 0 com.google.android.setupwizard
pm uninstall --user 0 com.google.android.syncadapters.calendar
pm uninstall --user 0 com.google.android.syncadapters.contacts
pm uninstall --user 0 com.google.android.tts
pm uninstall --user 0 com.google.ar.core
pm uninstall --user 0 com.google.mainline.telemetry
pm uninstall --user 0 com.hiya.star
pm uninstall --user 0 com.knox.vpn.proxyhandler
pm uninstall --user 0 com.mediatek
pm uninstall --user 0 com.mediatek.systemuiresoverlay
pm uninstall --user 0 com.microsoft.appmanager
pm uninstall --user 0 com.microsoft.skydrive
pm uninstall --user 0 com.monotype.android.font.foundation
pm uninstall --user 0 com.monotype.android.font.samsungone
pm uninstall --user 0 com.netflix.mediaclient
pm uninstall --user 0 com.netflix.partner.activation
pm uninstall --user 0 com.osp.app.signin
pm uninstall --user 0 com.samsung.aasaservice
pm uninstall --user 0 com.samsung.adaptivebrightnessgo
pm uninstall --user 0 com.samsung.advp.imssettings
pm uninstall --user 0 com.samsung.android.accessibility.talkback
pm uninstall --user 0 com.samsung.android.aircommandmanager
pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
pm uninstall --user 0 com.samsung.android.app.appsedge
pm uninstall --user 0 com.samsung.android.app.clipboardedge
pm uninstall --user 0 com.samsung.android.app.cocktailbarservice
pm uninstall --user 0 com.samsung.android.app.dressroom
pm uninstall --user 0 com.samsung.android.app.galaxyfinder
pm uninstall --user 0 com.samsung.android.app.omcagent
pm uninstall --user 0 com.samsung.android.app.reminder
pm uninstall --user 0 com.samsung.android.app.settings.bixby
pm uninstall --user 0 com.samsung.android.app.sharelive
pm uninstall --user 0 com.samsung.android.app.simplesharing
pm uninstall --user 0 com.samsung.android.app.smartcapture
pm uninstall --user 0 com.samsung.android.app.soundpicker
pm uninstall --user 0 com.samsung.android.app.spage
pm uninstall --user 0 com.samsung.android.app.taskedge
pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall --user 0 com.samsung.android.appseparation
pm uninstall --user 0 com.samsung.android.ardrawing
pm uninstall --user 0 com.samsung.android.aremoji
pm uninstall --user 0 com.samsung.android.aremojieditor
pm uninstall --user 0 com.samsung.android.arzone
pm uninstall --user 0 com.samsung.android.authfw
pm uninstall --user 0 com.samsung.android.aware.service
pm uninstall --user 0 com.samsung.android.bbc.bbcagent
pm uninstall --user 0 com.samsung.android.beaconmanager
pm uninstall --user 0 com.samsung.android.bixbyvision.framework
pm uninstall --user 0 com.samsung.android.bluelightfilter
pm uninstall --user 0 com.samsung.android.brightnessbackupservice
pm uninstall --user 0 com.samsung.android.callbgprovider
pm uninstall --user 0 com.samsung.android.cidmanager
pm uninstall --user 0 com.samsung.android.cmfa.framework
pm uninstall --user 0 com.samsung.android.container
pm uninstall --user 0 com.samsung.android.da.daagent
pm uninstall --user 0 com.samsung.android.dqagent
pm uninstall --user 0 com.samsung.android.dsms
pm uninstall --user 0 com.samsung.android.dynamiclock
pm uninstall --user 0 com.samsung.android.easysetup
pm uninstall --user 0 com.samsung.android.fmm
pm uninstall --user 0 com.samsung.android.forest
pm uninstall --user 0 com.samsung.android.game.gamehome
pm uninstall --user 0 com.samsung.android.game.gametools
pm uninstall --user 0 com.samsung.android.hdmapp
pm uninstall --user 0 com.samsung.android.icecone
pm uninstall --user 0 com.samsung.android.kidsinstaller
pm uninstall --user 0 com.samsung.android.knox.analytics.uploader
pm uninstall --user 0 com.samsung.android.knox.attestation
pm uninstall --user 0 com.samsung.android.knox.containeragent
pm uninstall --user 0 com.samsung.android.knox.containercore
pm uninstall --user 0 com.samsung.android.knox.pushmanager
pm uninstall --user 0 com.samsung.android.livestickers
pm uninstall --user 0 com.samsung.android.localeoverlaymanager
pm uninstall --user 0 com.samsung.android.location
pm uninstall --user 0 com.samsung.android.lool
pm uninstall --user 0 com.samsung.android.mapsagent
pm uninstall --user 0 com.samsung.android.mateagent
pm uninstall --user 0 com.samsung.android.mcfds
pm uninstall --user 0 com.samsung.android.mcfserver
pm uninstall --user 0 com.samsung.android.mdecservice
pm uninstall --user 0 com.samsung.android.mdm
pm uninstall --user 0 com.samsung.android.mdx
pm uninstall --user 0 com.samsung.android.mdx.kit
pm uninstall --user 0 com.samsung.android.mdx.quickboard
pm uninstall --user 0 com.samsung.android.mobileservice
pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider
pm uninstall --user 0 com.samsung.android.networkdiagnostic
pm uninstall --user 0 com.samsung.android.networkstack
pm uninstall --user 0 com.samsung.android.networkstack.tethering.overlay
pm uninstall --user 0 com.samsung.android.privateshare
pm uninstall --user 0 com.samsung.android.providers.carrier
pm uninstall --user 0 com.samsung.android.rubin.app
pm uninstall --user 0 com.samsung.android.samsungpass
pm uninstall --user 0 com.samsung.android.samsungpassautofill
pm uninstall --user 0 com.samsung.android.scloud
pm uninstall --user 0 com.samsung.android.scs
pm uninstall --user 0 com.samsung.android.sdk.handwriting
pm uninstall --user 0 com.samsung.android.sdm.config
pm uninstall --user 0 com.samsung.android.securitylogagent
pm uninstall --user 0 com.samsung.android.server.wifi.mobilewips
pm uninstall --user 0 com.samsung.android.service.peoplestripe
pm uninstall --user 0 com.samsung.android.service.stplatform
pm uninstall --user 0 com.samsung.android.setting.multisound
pm uninstall --user 0 com.samsung.android.SettingsReceiver
pm uninstall --user 0 com.samsung.android.shortcutbackupservice
pm uninstall --user 0 com.samsung.android.sm.devicesecurity
pm uninstall --user 0 com.samsung.android.sm.policy
pm uninstall --user 0 com.samsung.android.smartcallprovider
pm uninstall --user 0 com.samsung.android.smartface
pm uninstall --user 0 com.samsung.android.smartmirroring
pm uninstall --user 0 com.samsung.android.smartsuggestions
pm uninstall --user 0 com.samsung.android.smartswitchassistant
pm uninstall --user 0 com.samsung.android.spayfw
pm uninstall --user 0 com.samsung.android.stickercenter
pm uninstall --user 0 com.samsung.android.svcagent
pm uninstall --user 0 com.samsung.android.tadownloader
pm uninstall --user 0 com.samsung.android.tapack.authfw
pm uninstall --user 0 com.samsung.android.themecenter
pm uninstall --user 0 com.samsung.android.themestore
pm uninstall --user 0 com.samsung.android.uds
pm uninstall --user 0 com.samsung.android.visionintelligence
pm uninstall --user 0 com.samsung.android.wallpaper.res
pm uninstall --user 0 com.samsung.android.wifi.resources
pm uninstall --user 0 com.samsung.android.wifi.softap.resources
pm uninstall --user 0 com.samsung.cmh
pm uninstall --user 0 com.samsung.crane
pm uninstall --user 0 com.samsung.faceservice
pm uninstall --user 0 com.samsung.ims.smk
pm uninstall --user 0 com.samsung.internal.systemui.navbar.gestural_no_hint
pm uninstall --user 0 com.samsung.internal.systemui.navbar.gestural_no_hint_extra_wide_back
pm uninstall --user 0 com.samsung.internal.systemui.navbar.gestural_no_hint_narrow_back
pm uninstall --user 0 com.samsung.internal.systemui.navbar.gestural_no_hint_wide_back
pm uninstall --user 0 com.samsung.internal.systemui.navbar.sec_gestural
pm uninstall --user 0 com.samsung.internal.systemui.navbar.sec_gestural_no_hint
pm uninstall --user 0 com.samsung.ipservice
pm uninstall --user 0 com.samsung.klmsagent
pm uninstall --user 0 com.samsung.knox.keychain
pm uninstall --user 0 com.samsung.knox.securefolder
pm uninstall --user 0 com.samsung.memorysaver
pm uninstall --user 0 com.samsung.rcs
pm uninstall --user 0 com.samsung.safetyinformation
pm uninstall --user 0 com.samsung.sec.android.application.csc
pm uninstall --user 0 com.samsung.SMT
pm uninstall --user 0 com.samsung.storyservice
pm uninstall --user 0 com.sec.android.app.billing
pm uninstall --user 0 com.sec.android.app.bluetoothtest
pm uninstall --user 0 com.sec.android.app.chromecustomizations
pm uninstall --user 0 com.sec.android.app.DataCreate
pm uninstall --user 0 com.sec.android.app.factorykeystring
pm uninstall --user 0 com.sec.android.app.fm
pm uninstall --user 0 com.sec.android.app.hwmoduletest
pm uninstall --user 0 com.sec.android.app.magnifier
pm uninstall --user 0 com.sec.android.app.parser
pm uninstall --user 0 com.sec.android.app.personalization
pm uninstall --user 0 com.sec.android.app.quicktool
pm uninstall --user 0 com.sec.android.app.ringtoneBR
pm uninstall --user 0 com.sec.android.app.safetyassurance
pm uninstall --user 0 com.sec.android.app.SecSetupWizard
pm uninstall --user 0 com.sec.android.app.servicemodeapp
pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider
pm uninstall --user 0 com.sec.android.app.soundalive
pm uninstall --user 0 com.sec.android.app.ve.vebgm
pm uninstall --user 0 com.sec.android.app.wlantest
pm uninstall --user 0 com.sec.android.autodoodle.service
pm uninstall --user 0 com.sec.android.daemonapp
pm uninstall --user 0 com.sec.android.diagmonagent
pm uninstall --user 0 com.sec.android.easyMover.Agent
pm uninstall --user 0 com.sec.android.emergencylauncher
pm uninstall --user 0 com.sec.android.emergencymode.service
pm uninstall --user 0 com.sec.android.mimage.avatarstickers
pm uninstall --user 0 com.sec.android.preloadinstaller
pm uninstall --user 0 com.sec.android.provider.badge
pm uninstall --user 0 com.sec.android.provider.emergencymode
pm uninstall --user 0 com.sec.android.RilServiceModeApp
pm uninstall --user 0 com.sec.android.soagent
pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
pm uninstall --user 0 com.sec.android.widgetapp.webmanual
pm uninstall --user 0 com.sec.app.RilErrorNotifier
pm uninstall --user 0 com.sec.automation
pm uninstall --user 0 com.sec.bcservice
pm uninstall --user 0 com.sec.enterprise.knox.attestation
pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm uninstall --user 0 com.sec.enterprise.mdm.services.simpin
pm uninstall --user 0 com.sec.epdg
pm uninstall --user 0 com.sec.epdgtestapp
pm uninstall --user 0 com.sec.factory
pm uninstall --user 0 com.sec.factory.camera
pm uninstall --user 0 com.sec.factory.cameralyzer
pm uninstall --user 0 com.sec.hearingadjust
pm uninstall --user 0 com.sec.imslogger
pm uninstall --user 0 com.sec.imsservice
pm uninstall --user 0 com.sec.location.nfwlocationprivacy
pm uninstall --user 0 com.sec.location.nsflp2
pm uninstall --user 0 com.sec.mhs.smarttethering
pm uninstall --user 0 com.sec.phone
pm uninstall --user 0 com.sec.spp.push
pm uninstall --user 0 com.sec.sve
pm uninstall --user 0 com.sec.unifiedwfc
pm uninstall --user 0 com.sec.vsim.ericssonnsds.webapp
pm uninstall --user 0 com.skms.android.agent
pm uninstall --user 0 com.trustonic.teeservice
pm uninstall --user 0 com.wsomacp
pm uninstall --user 0 com.wssyncmldm
